AWSTemplateFormatVersion: '2010-09-09'
Description: Classic Load Balancer for nginx-service

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: k8s-demo

Resources:
  ELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SubnetId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PublicSubnet1Id"
      SecurityGroups:
        - !Ref ELBSecurityGroup
      Listeners:
        - LoadBalancerPort: 80
          InstancePort: 30201
          Protocol: TCP
      HealthCheck:
        Target: TCP:30201
        HealthyThreshold: 3
        UnhealthyThreshold: 5
        Interval: 30
        Timeout: 5
      Instances:
        - Fn::ImportValue:
            !Sub "${EnvironmentName}-ControlPlaneId"

  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic to the ELB
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  LoadBalancerDNSName:
    Description: DNS Name of the Load Balancer
    Value: !GetAtt NginxELB.DNSName
    Export:
      Name: !Sub "${EnvironmentName}-LoadBalancerDNSName"